const staticData = [
  {
    popularity: 225.007,
    vote_count: 15060,
    video: false,
    poster_path: "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    id: 299534,
    adult: false,
    backdrop_path: "/orjiB3oUIsyz60hoEqkiGpy5CeO.jpg",
    original_language: "en",
    original_title: "Avengers: Endgame",
    genre_ids: [28, 12, 878],
    title: "Avengers: Endgame",
    vote_average: 8.3,
    overview:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    release_date: "2019-04-24",
  },
  {
    popularity: 250.634,
    vote_count: 19689,
    video: false,
    poster_path: "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    id: 299536,
    adult: false,
    backdrop_path: "/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg",
    original_language: "en",
    original_title: "Avengers: Infinity War",
    genre_ids: [28, 12, 878],
    title: "Avengers: Infinity War",
    vote_average: 8.3,
    overview:
      "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
    release_date: "2018-04-25",
  },
  {
    popularity: 112.636,
    vote_count: 23156,
    video: false,
    poster_path: "/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
    id: 24428,
    adult: false,
    backdrop_path: "/kwUQFeFXOOpgloMgZaadhzkbTI4.jpg",
    original_language: "en",
    original_title: "The Avengers",
    genre_ids: [28, 12, 878],
    title: "The Avengers",
    vote_average: 7.7,
    overview:
      "When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!",
    release_date: "2012-04-25",
  },
  {
    popularity: 88.542,
    vote_count: 16526,
    video: false,
    poster_path: "/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg",
    id: 99861,
    adult: false,
    backdrop_path: "/8i6ZDk97Vyh0jHohMG4vFeFuKJh.jpg",
    original_language: "en",
    original_title: "Avengers: Age of Ultron",
    genre_ids: [28, 12, 878],
    title: "Avengers: Age of Ultron",
    vote_average: 7.3,
    overview:
      "When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.",
    release_date: "2015-04-22",
  },
  {
    popularity: 30.843,
    vote_count: 75,
    video: false,
    poster_path: "/1SbBKCbnULACOqWKN7eLfTu1gVm.jpg",
    id: 323660,
    adult: false,
    backdrop_path: "/tui9Z2QEoZSIPZMfpvPcNP9HIoA.jpg",
    original_language: "en",
    original_title: "Avengers Grimm",
    genre_ids: [28, 14],
    title: "Avengers Grimm",
    vote_average: 4.1,
    overview:
      'When Rumpelstiltskin destroys the Magic Mirror and escapes to the modern world, the four princesses of "Once Upon a Time"-Cinderella, Sleeping Beauty, Snow White, and Rapunzel-are sucked through the portal too. Well-trained and endowed with magical powers, the four women must fight Rumpelstiltskin and his army of thralls before he enslaves everyone on Earth.',
    release_date: "2015-03-17",
  },
  {
    popularity: 21.661,
    vote_count: 441,
    video: false,
    poster_path: "/1p5thyQ4pCy876HpdvFARqJ62N9.jpg",
    id: 9320,
    adult: false,
    backdrop_path: "/fryen9fnjlm0YibKTDNGzWNBOSo.jpg",
    original_language: "en",
    original_title: "The Avengers",
    genre_ids: [878, 53],
    title: "The Avengers",
    vote_average: 4.3,
    overview:
      'British Ministry agent John Steed, under direction from "Mother", investigates a diabolical plot by arch-villain Sir August de Wynter to rule the world with his weather control machine. Steed investigates the beautiful Doctor Mrs. Emma Peel, the only suspect, but simultaneously falls for her and joins forces with her to combat Sir August.',
    release_date: "1998-08-13",
  },
  {
    popularity: 19.8,
    vote_count: 220,
    video: false,
    poster_path: "/iMCkGHVrYRdqKROPRPmVaJVSlg3.jpg",
    id: 14609,
    adult: false,
    backdrop_path: "/p5uTZHrXwWX0j9dYZK8yx22sO7T.jpg",
    original_language: "en",
    original_title: "Ultimate Avengers: The Movie",
    genre_ids: [28, 12, 16, 878],
    title: "Ultimate Avengers: The Movie",
    vote_average: 6.7,
    overview:
      "When a nuclear missile was fired at Washington in 1945, Captain America managed to detonate it in the upper atmosphere. But then he fell miles into the icy depths of the North Atlantic, where he remained lost for over sixty years. But now, with the world facing the very same evil, Captain America must rise again as our last hope for survival.",
    release_date: "2006-02-21",
  },
  {
    popularity: 12.479,
    vote_count: 10,
    video: false,
    poster_path: "/ehTYWuPKwl8sXPX0I6LnvJUDaVl.jpg",
    id: 347158,
    adult: false,
    backdrop_path: null,
    original_language: "en",
    original_title: "Bikini Avengers",
    genre_ids: [35],
    title: "Bikini Avengers",
    vote_average: 5.7,
    overview:
      "When the Jade Empress steals the world's largest diamonds, super heroes Bikini Avenger and Thong Girl must stop her before she uses the gems to build a dangerous sci-fi weapon.",
    release_date: "2015-02-24",
  },
  {
    popularity: 13.609,
    vote_count: 36,
    video: false,
    poster_path: "/xfAcu74DRQXeM9XqFcE5MrSRzYP.jpg",
    id: 521720,
    adult: false,
    backdrop_path: "/mdSrxMg4l6a76AFoBWmu7Q1X4Rt.jpg",
    original_language: "en",
    original_title: "Avengers Grimm: Time Wars",
    genre_ids: [28, 12, 14],
    title: "Avengers Grimm: Time Wars",
    vote_average: 4.7,
    overview:
      "When Rumpelstiltskin tries to take over Earth once and for all, The Avengers Grimm must track him down through time in order to defeat him.",
    release_date: "2018-05-01",
  },
  {
    popularity: 17.786,
    vote_count: 133,
    video: false,
    poster_path: "/fpG1NDbcLV2a7c8X7LC4FPISBT7.jpg",
    id: 14613,
    adult: false,
    backdrop_path: "/8N91uYwrr1uepEKbmym1tgfXlzS.jpg",
    original_language: "en",
    original_title: "Next Avengers: Heroes of Tomorrow",
    genre_ids: [16, 10751],
    title: "Next Avengers: Heroes of Tomorrow",
    vote_average: 6.7,
    overview:
      "The children of the Avengers hone their powers and go head to head with the very enemy responsible for their parents' demise.",
    release_date: "2008-09-02",
  },
  {
    popularity: 18.971,
    id: 14611,
    video: false,
    vote_count: 184,
    vote_average: 6.6,
    title: "Ultimate Avengers 2: Rise of the Panther",
    release_date: "2006-08-08",
    original_language: "en",
    original_title: "Ultimate Avengers 2: Rise of the Panther",
    genre_ids: [12, 16, 28, 878],
    backdrop_path: "/z1P4mdithLear5Du48jbsIr12b7.jpg",
    adult: false,
    overview:
      "Mysterious Wakanda lies in the darkest heart of Africa, unknown to most of the world. An isolated land hidden behind closed borders, fiercely protected by its young king - the Black Panther. But when brutal alien invaders attack, the threat leaves the Black Panther with no option but to go against the sacred decrees of his people and ask for help from outsiders.",
    poster_path: "/sMFyYZR9krqcQC99G6jnb10Zv4P.jpg",
  },
  {
    popularity: 13.356,
    vote_count: 42,
    video: false,
    poster_path: "/xUBZNoY7idPfqKZepnDEv7Qc8GC.jpg",
    id: 368304,
    adult: false,
    backdrop_path: "/zvjBC9guJVw32bZu4ODp6wzJ9Vi.jpg",
    original_language: "en",
    original_title: "LEGO Marvel Super Heroes: Avengers Reassembled!",
    genre_ids: [16],
    title: "LEGO Marvel Super Heroes: Avengers Reassembled!",
    vote_average: 6.3,
    overview:
      "In \"LEGO Marvel Super Heroes: Avengers Reassembled!,\" the Avengers prepare for a party at Stark Tower and notice that Iron Man is acting strange. After some investigation, they discover that the evil Ultron has taken control of Iron Man and his armor as part of his scheme to take over the world. It's up to Captain America, the Hulk, Thor, Vision, Black Widow, Hawkeye and their friends (Spider-Man, Iron Spider, and special guest star Ant-Man) to rescue Iron Man from Ultron's clutches and defeat the super villain before he causes even more destruction and chaos.",
    release_date: "2015-11-16",
  },
  {
    popularity: 13.312,
    id: 448368,
    video: true,
    vote_count: 9,
    vote_average: 8.4,
    title: "The Avengers: A Visual Journey",
    release_date: "2012-09-25",
    original_language: "en",
    original_title: "The Avengers: A Visual Journey",
    genre_ids: [],
    backdrop_path: null,
    adult: false,
    overview:
      "Joss Whedon and others in interviews discussing the aims for this new franchise.",
    poster_path: "/2kBT7KONKQTIhkMc2ZtPU11E8Ky.jpg",
  },
  {
    popularity: 4.192,
    vote_count: 1,
    video: false,
    poster_path: "/4L3ajGP3ZsnM8xIrXjwEZOLYBjb.jpg",
    id: 223291,
    adult: false,
    backdrop_path: null,
    original_language: "en",
    original_title: "Alien Avengers II",
    genre_ids: [35, 878, 10770],
    title: "Alien Avengers II",
    vote_average: 10,
    overview:
      'Weird things are happening in the town of Justice, Arizona: three sheriffs have disappeared, and someone is killing the rancher\'s livestock in a bizarre, ritualistic fashion. Locals believe the incidents were caused by aliens...\r But a visiting couple, Charlie and Rhonda, knows better – because they\'re aliens themselves. When no one else will, Charlie and Rhonda volunteer to be the new sheriffs to get to bottom of the crimes. Hiding behind the power of the badge, the two make their own rules, punishing wrong-doers with their own form of "eye-for-an-eye" alien vengeance.\r Follow this twisted, outer space "Bonnie and Clyde" as they attempt to bring Justice the justice it deserves.',
    release_date: "1997-10-25",
  },
  {
    popularity: 9.846,
    vote_count: 16,
    video: true,
    poster_path: "/2RDUQpzhJHVzObkL4ZxwJkbKYSz.jpg",
    id: 448366,
    adult: false,
    backdrop_path: null,
    original_language: "en",
    original_title: "Building the Dream: Assembling the Avengers",
    genre_ids: [99],
    title: "Building the Dream: Assembling the Avengers",
    vote_average: 8.4,
    overview:
      "This 90-minute feature will show how the films Iron Man, The Incredible Hulk, Iron Man 2, Thor, and Captain America: The First Avenger were conceived and led to the greatest super hero team ever assembled on screen The Avengers.",
    release_date: "2012-09-25",
  },
  {
    popularity: 7.166,
    id: 487555,
    video: false,
    vote_count: 1,
    vote_average: 8,
    title: "The Avengers: Earth's Mightiest Heroes - Prelude",
    release_date: "2010-09-22",
    original_language: "en",
    original_title: "The Avengers: Earth's Mightiest Heroes - Prelude",
    genre_ids: [16, 28],
    backdrop_path: null,
    adult: false,
    overview:
      'A 110 minute prelude to the 2010 animated series, consisting of five-and-a-half-minute chapters created from footage from season-one episodes, premiered online and on Disney XD on September 22, 2010. Series supervising producer Josh Fine said the goal was to "let us explore the individual members of the team in their own ongoing adventures ... do a lot of character development and set the stage for the rest of the season".',
    poster_path: "/3o7MpOaDkeAcvxqEjgbIcXrcepB.jpg",
  },
  {
    popularity: 2.523,
    vote_count: 3,
    video: false,
    poster_path: "/Akd3Aqrr2q8PLKOCPOkOnB3AoJk.jpg",
    id: 58906,
    adult: false,
    backdrop_path: "/boX7D2wHtf01C7AzzPuVZAzc74x.jpg",
    original_language: "en",
    original_title: "Alien Avengers",
    genre_ids: [35, 878],
    title: "Alien Avengers",
    vote_average: 5.3,
    overview:
      "Charlie and Rhonda are a sweet and comfortable married couple on vacation with their lovely daughter Daphne. They find a rundown boarding house and its haggard owner, Joseph, an ex-con whose mother has just died and left him the house. He doesn't know why this cheerful couple would want to vacation in the worst part of Los Angeles, but he doesn't know they're vacationing from outer space, and their idea of fun is murdering lowlife out on the streets",
    release_date: "1996-08-03",
  },
  {
    popularity: 5.389,
    vote_count: 6,
    video: false,
    poster_path: "/yymsCwKPbJIF1xcl2ih8fl7OxAa.jpg",
    id: 538153,
    adult: false,
    backdrop_path: "/fYczICEZAgmDh7lvQVlY9objtlF.jpg",
    original_language: "en",
    original_title: "Avengers of Justice: Farce Wars",
    genre_ids: [35, 14],
    title: "Avengers of Justice: Farce Wars",
    vote_average: 4.7,
    overview:
      "While trying to remain a good husband and father, Superbat and the Avengers of Justice come out of retirement to stop Dark Jokester and Lisp Luthor from freezing the planet.",
    release_date: "2018-07-20",
  },
  {
    popularity: 1.741,
    vote_count: 1,
    video: false,
    poster_path: null,
    id: 432413,
    adult: false,
    backdrop_path: null,
    original_language: "en",
    original_title: "The Avengers",
    genre_ids: [12],
    title: "The Avengers",
    vote_average: 10,
    overview:
      "The attractive Argentine Don Careless is an adventurer and an excellent swordsman. Don is in love with Maria Moreno, since he had to emerge her jewels and had thereby to kill a shark. Don tries to prevent the forced marriage of Mary with the ruthless revolutionary Colonel Luis Corral. An armed clash between Don and Luis seems inevitable.",
    release_date: "1950-06-10",
  },
  {
    popularity: 1.304,
    vote_count: 0,
    video: false,
    poster_path: null,
    id: 648416,
    adult: false,
    backdrop_path: null,
    original_language: "en",
    original_title: "New Avengers",
    genre_ids: [],
    title: "New Avengers",
    vote_average: 0,
    overview:
      "When Kang threatens the timeline of young heroes, much lies ahead",
    release_date: "",
  },
];

export default staticData;
